if(DEFINED DAQMODULES_LT_STREAMING_CMAKE_OPTIONS_INCLUDED)
    return()
endif()
set(DAQMODULES_LT_STREAMING_CMAKE_OPTIONS_INCLUDED TRUE)

cmake_dependent_option(
    DAQMODULES_LT_STREAMING_ENABLE_SIGGEN_INTEGRATION_TESTS
    "Enable websocket streaming integration tests"
    ON
    "OPENDAQ_ENABLE_TESTS AND DAQMODULES_LT_STREAMING_BUILDING_AS_SUBMODULE OR DAQMODULES_LT_STREAMING_ENABLE_TESTS AND NOT DAQMODULES_LT_STREAMING_BUILDING_AS_SUBMODULE"
    OFF
)
